[WIP] Developer docs
nfdi4plants/ARCtrl pull request #228
Opened 2023-10-09 14:18 UTC by Freymaurer

Starting to write developer docs. Until Fable allows keeping comments, auto generated source code docs do not seem like a valid option.

@JonasLukasczyk please have a look at the js code implementation `/docs/scripts_js/ARC.js` and please just sent me all of your ARCtrl code implementations.

@HLWeil tell me if you are okay with the structur, file placement, etc.

closes #223 
closes #231 
closes #233 
closes #234 
closes #232 
closes #114

2023-10-10 07:34 UTC, HLWeil requested changes
I think we should add direct links from the main `README.md` to the `.md` files located in the docs folder.
Similar to https://github.com/fslaborg/FSharp.Stats

2023-10-10 07:34 UTC, HLWeil commented on docs/ARC.md
> +In .NET you can use [ARCtrl.NET][1] to handle any contract based read/write operations. For this documentation we will extract the relevant ARCtrl.NET functions.
Maybe we actually also add documentation for ARCtrl.Net here?

2023-10-10 07:35 UTC, HLWeil commented
Maybe split ARC.md into `IO.md` and `API.md`?

2023-10-27 14:14 UTC, Freymaurer commented
@HLWeil can you review this, so we can just release a new beta version and i will add some more docs soon?

2023-10-27 17:21 UTC, HLWeil approved these changes
Good starting point for the documentation. We should keep in mind to reorganize a bit (especially root README.md) when we get a little bit more bulk.

2023-10-27 17:21 UTC, merged

2023-10-27 20:07 UTC, Freymaurer commented
> Good starting point for the documentation. We should keep in mind to reorganize a bit (especially root README.md) when we get a little bit more bulk.

Damn! I forgot to push my last changes to README.md!