Python integration
nfdi4plants/ARCtrl pull request #317
Opened 2024-03-01 13:09 UTC by HLWeil

- Setup `build` and `test` targets for `Python`
- Full integration of Fable transpilation to `Python`
- Extended developer setup instructions
- Moved JsonSchemaValidation to tests

2024-03-01 13:19 UTC, HLWeil commented
CI needs to be updated

2024-03-07 10:50 UTC, Freymaurer requested changes

2024-03-07 10:50 UTC, Freymaurer commented on build/GenerateIndexPy.fs
> +    |> writePyIndexfile rootPath
🚀

2024-03-07 10:50 UTC, Freymaurer commented on build/ProjectInfo.fs
> +let netPkgDir = "dist/pkg"
no relative path?

2024-03-07 10:50 UTC, Freymaurer commented on pyproject.toml
> +authors = ["Heinrich Lukas Weil <weil@rptu.de>"]
freymaurer@gmx.de

2024-03-07 10:50 UTC, Freymaurer commented on pytests/arc_table_tests.ipynb
Should this file be on .gitignore?

2024-03-07 10:50 UTC, Freymaurer commented on pytests/composite_header_tests.ipynb
Same

2024-03-07 10:50 UTC, Freymaurer commented on README.md
> +    - verify with `py --version` (Tested with 3.12.2)
Add a note for minimal 3.11.x

2024-03-07 10:50 UTC, Freymaurer commented on src/ARCtrl/WebRequest/WebRequest.Py.fs
> +module Interop =
maybe we should do the same for the web request library from Zaid (copy paste the relevant code). Then we could implement the nodejs part in a cleaner way.

2024-03-07 13:18 UTC, HLWeil commented on pytests/arc_table_tests.ipynb
Removed the whole folder and setup file. Was there for initial testing

2024-03-07 13:34 UTC, HLWeil commented on src/Contract/Contract.fs
>      [<NamedParams(fromIndex=2)>]
Yup, there were some problems. Will make a note

2024-03-07 13:50 UTC, HLWeil commented on testpy.cmd
Removed

2024-03-07 13:54 UTC, HLWeil commented on tests/ISA/ISA.Json.Tests/ArcTypes.Tests.fs
> +        #if FABLE_COMPILER_JAVASCRIPT
Will move all of this into a performance checking project anyways.

2024-03-07 13:56 UTC, Freymaurer commented on src/Contract/Contract.fs
>      [<NamedParams(fromIndex=2)>]
yeah exactly 🙂

2024-03-07 13:58 UTC, HLWeil commented on src/ISA/ISA/Fable.fs
> +             a |> List.ofArray |> List.sort |> Array.ofList
https://github.com/fable-compiler/Fable/issues/3638

Seems to be fixed now.

2024-03-08 13:27 UTC, Freymaurer requested changes

2024-03-08 13:27 UTC, Freymaurer commented on build/release_package.json
> +  "version": "1.2.0+19d850e",
use short semver without metadata

2024-03-08 13:28 UTC, HLWeil commented
Done, will be updated with next version tick.

2024-03-08 13:34 UTC, Freymaurer approved these changes
lets go! 🚀

2024-03-08 13:43 UTC, merged