Rework data nodes
nfdi4plants/ARCtrl pull request #356
Opened 2024-05-06 09:20 UTC by HLWeil

replace "Raw Data File", "Derived Data File" and "Image File" column headers with "Data"

[#93](https://github.com/nfdi4plants/ARC-specification/pull/93)

2024-05-06 11:04 UTC, Freymaurer requested changes
Did you write tests to check if backwards compatibility is maintained?

2024-05-06 11:04 UTC, Freymaurer commented on src/Core/Conversion.fs
> +        | CompositeHeader.Output IOType.Data -> ProcessOutput.createDerivedData(value.ToString())
![image](https://github.com/nfdi4plants/ARCtrl/assets/39732517/990510b3-ae68-42c7-92f9-7f8c8fbaf37e)

2024-05-06 11:18 UTC, HLWeil commented on src/Core/Conversion.fs
> +        | CompositeHeader.Output IOType.Data -> ProcessOutput.createDerivedData(value.ToString())
Will do!

2024-05-15 08:00 UTC, Freymaurer requested changes
![image](https://github.com/nfdi4plants/ARCtrl/assets/39732517/d28a9bbe-8f39-4f87-86cf-995dfd4397d8)

2024-05-27 08:27 UTC, HLWeil commented on src/Core/Table/CompositeCell.fs
> +    | Data of Data
Will do!

2024-05-27 08:28 UTC, HLWeil commented on src/Core/Process/Data.fs
> +namespace ARCtrl
Because the type is now also used in the ArcTable. But as it is now being referenced both from ArcTable and Process, placing it is a bit difficult.

2024-05-28 11:16 UTC, Freymaurer requested changes
Move files outside process folder if they are used in ArcTypes... plus:

![image](https://github.com/nfdi4plants/ARCtrl/assets/39732517/33c2795c-8890-4e27-84bd-8df3239d0431)

2024-05-28 14:59 UTC, Freymaurer approved these changes

2024-05-29 06:11 UTC, merged